'use client';

import { useEffect, useMemo, useState } from 'react';
import { DashboardLayout } from '@/components/dashboard-layout';
import { PageHeader } from '@/components/page-header';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { MetricCard } from '@/components/metric-card';
import { EmptyState } from '@/components/state-components';
import { Plus, PiggyBank, Trash2 } from 'lucide-react';
import { addRecord, deleteRecord, formatRecordError, listRecords, toNumber, updateRecord, validateAmount, type FinancialRecord } from '@/lib/financial-data';
import { formatCurrency } from '@/lib/format';

export default function SavingsPage() {
  const [savings, setSavings] = useState<FinancialRecord[]>([]); const [amount, setAmount] = useState(''); const [savingsType, setSavingsType] = useState('Total Savings'); const [recordDate, setRecordDate] = useState(new Date().toISOString().slice(0, 10)); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [editingId, setEditingId] = useState<string | null>(null);
  useEffect(() => { void listRecords('savings_records').then(setSavings).catch((err) => setError(formatRecordError(err))).finally(() => setLoading(false)); }, []);
  const totalSavings = useMemo(() => savings.filter((item) => item.savings_type !== 'Monthly Savings').reduce((sum, item) => sum + toNumber(item.amount), 0), [savings]);
  const monthlySavings = useMemo(() => savings.filter((item) => item.savings_type === 'Monthly Savings').reduce((sum, item) => sum + toNumber(item.amount), 0), [savings]);
  const emergencyFund = useMemo(() => savings.filter((item) => item.savings_type === 'Emergency Fund').reduce((sum, item) => sum + toNumber(item.amount), 0), [savings]);
  async function save() { if (!validateAmount(amount) || !recordDate) { setError('Enter a positive amount and a valid date.'); return; } setSaving(true); setError(''); try { const payload = { amount: Number(amount), savings_type: savingsType, record_date: recordDate }; const record = editingId ? await updateRecord('savings_records', editingId, payload) : await addRecord('savings_records', payload); setSavings((current) => editingId ? current.map((item) => item.id === editingId ? record : item) : [record, ...current]); setAmount(''); setEditingId(null); } catch (err) { setError(formatRecordError(err)); } finally { setSaving(false); } }
  async function remove(id: string) { if (!window.confirm('Delete this savings record?')) return; try { await deleteRecord('savings_records', id); setSavings((current) => current.filter((item) => item.id !== id)); } catch (err) { setError(formatRecordError(err)); } }
  return <DashboardLayout><PageHeader title="Savings" description="Track your savings and emergency fund."><Button onClick={save} disabled={saving}><Plus className="mr-2 h-4 w-4" />Add Savings Record</Button></PageHeader>{error && <p role="alert" className="mt-4 rounded-md border border-danger/30 bg-danger/5 p-3 text-sm text-danger">{error}</p>}<div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><MetricCard title="Total Savings" value={formatCurrency(totalSavings)} icon={<PiggyBank className="h-4 w-4" />} accent="success" /><MetricCard title="Emergency Fund" value={formatCurrency(emergencyFund)} accent="primary" /><MetricCard title="Monthly Savings" value={formatCurrency(monthlySavings)} accent="success" /></div><Card className="mt-6"><CardHeader><CardTitle className="text-base">Add Savings Record</CardTitle></CardHeader><CardContent><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><div className="space-y-2"><Label htmlFor="sav-amount">Amount (₹)</Label><Input id="sav-amount" type="number" min="0" value={amount} onChange={(e) => setAmount(e.target.value)} /></div><div className="space-y-2"><Label htmlFor="sav-type">Savings Type</Label><Select value={savingsType} onValueChange={setSavingsType}><SelectTrigger id="sav-type"><SelectValue /></SelectTrigger><SelectContent>{['Total Savings', 'Emergency Fund', 'Monthly Savings', 'Goal Savings'].map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label htmlFor="sav-date">Date</Label><Input id="sav-date" type="date" value={recordDate} onChange={(e) => setRecordDate(e.target.value)} /></div></div><Button className="mt-4" onClick={save} disabled={saving}><Plus className="mr-2 h-4 w-4" />Save Record</Button></CardContent></Card><Card className="mt-6"><CardHeader><CardTitle className="text-base">Savings Records</CardTitle></CardHeader><CardContent>{loading ? <p className="text-sm text-muted-foreground">Loading savings…</p> : savings.length === 0 ? <EmptyState icon={<PiggyBank className="h-6 w-6" />} title="No savings recorded" description="Add your first savings record to start tracking progress." /> : <Table><TableHeader><TableRow><TableHead>Type</TableHead><TableHead>Amount</TableHead><TableHead>Date</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{savings.map((item) => <TableRow key={item.id}><TableCell className="font-medium">{String(item.savings_type)}</TableCell><TableCell>{formatCurrency(toNumber(item.amount))}</TableCell><TableCell>{String(item.record_date)}</TableCell><TableCell className="text-right"><Button variant="ghost" size="icon" onClick={() => remove(item.id)} aria-label="Delete savings record"><Trash2 className="h-4 w-4 text-danger" /></Button></TableCell></TableRow>)}</TableBody></Table>}</CardContent></Card></DashboardLayout>;
}
